Repository ITU-BDSA2024-GROUP4/Chirp, pull requests merged in 2024-11, with the labels that each got.

#185 181 as a user i wanna see a like and cheep counter
  src/Chirp.Core/ICheepRepository.cs
  src/Chirp.Core/ICheepService.cs
  src/Chirp.Infrastructure/CheepRepository.cs
  src/Chirp.Infrastructure/CheepService.cs
  src/Chirp.Web/Pages/About.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: enhancement

#186 Fix login and logout in register and login page
  src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs
Labels: bug, default, Fixed, AwaitingPullRequest

#187 183 fix same user can follow someone an infinite amount of time
  src/Chirp.Core/ICheepRepository.cs
  src/Chirp.Core/ICheepService.cs
  src/Chirp.Core/Schema.cs
  src/Chirp.Infrastructure/CheepRepository.cs
  src/Chirp.Infrastructure/CheepService.cs
  src/Chirp.Infrastructure/ChirpDBContext.cs
  src/Chirp.Infrastructure/Migrations/20241129232659_init.Designer.cs
  src/Chirp.Infrastructure/Migrations/20241129232659_init.cs
  src/Chirp.Infrastructure/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
  test/Chirp.Tests/CheepRepositoryUnitTests.cs
Labels: bug, default, Fixed, AwaitingPullRequest

#190 Fixed failing playwright test and added new github action specificall…
  .github/workflows/build_and_test.yml
  .github/workflows/playwright_tests.yml
  Solution.sln
  src/Chirp.Web/Chirp.Web.sln
  test/Chirp.Tests/Chirp.Tests.sln
  test/PlaywrightTests/PlaywrightTests.csproj
  test/PlaywrightTests/UITests.cs
Labels: Fixed
